# Generated by Django 4.2.11 on 2024-04-24 20:03

from django.db import migrations
import react_wod.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', react_wod.users.models.UserManager()),
            ],
        ),
    ]
