# Generated by Django 4.2.11 on 2024-05-09 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrix',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='file_contents',
            field=models.TextField(blank=True, default='', help_text='Markdown content of the file goes here'),
        ),
        migrations.AddField(
            model_name='document',
            name='matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='matrix.matrix'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_matricies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='matrix.document')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='matrix.matrix')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='matrix.document')),
            ],
        ),
    ]
