# Generated by Django 4.2.11 on 2024-04-10 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrix',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='file_contents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='document',
            name='matrix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='matrix.matrix'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='matrix.document')),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='matrix.matrix')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='matrix.document')),
            ],
        ),
    ]
