# Generated by Django 4.2.11 on 2024-04-24 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import matrix.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matrix', '0002_remove_matrix_documents_document_file_contents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(default=matrix.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_contents',
            field=models.TextField(blank=True, help_text='Markdown content of the file goes here'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_name',
            field=models.CharField(help_text='Enter the filename', max_length=200),
        ),
        migrations.AlterField(
            model_name='matrix',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_matricies', to=settings.AUTH_USER_MODEL),
        ),
    ]
