# Generated by Django 4.2.11 on 2024-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_document_owner_alter_matrix_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_contents',
            field=models.TextField(blank=True, default='', help_text='Markdown content of the file goes here'),
        ),
    ]
